version: '3.3'

services:
  app:
    image: forum_monitoring_tools
    container_name: forum_monitoring_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./screenshots:/app/screenshots
    ports:
      - "8080:8080"
    environment:
      - TOR_PROXY=socks5://127.0.0.1:9050
